[package]
name = "cometahn142/nexus"
description = "Nexus For Roblox"
version = "0.2.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["src", "default.project.json", "LICENSE", "README.md"]

[dependencies]
Signal = "cometahn142/signal@^0.1"
Promise = "cometahn142/promise@^0.1"
Janitor = "cometahn142/janitor@^0.1"
Snap = "cometahn142/snap@^0.2"
